apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app
  namespace: argocd
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  project: default
  source:
    repoURL: 'https://github.com/grvsobha/microservices-demo.git'
    path: path/to/your/app
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  plugin:
    name: 'helm'
    env:
      - name: HELM_EXPERIMENTAL_OCI
        value: '1'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd

