apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: myc1
        image: docker.io/z12bsobh/nginx:latest
        imagePullPolicy: IfNotPresent
        envFrom:
        - secretRef:
            name: dockerhub-credentials

