apiVersion: v1
kind: Service
metadata:
  name: mysvc
spec:
  selector:
    app: web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080  # Adjust this based on your application's port
  type: LoadBalancer  # or NodePort, ClusterIP, etc.
