apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-app1
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: default
  project: default
  source:
    repoURL: 'https://github.com/grvsobha/microservices-demo.git'
    path: kubernetes-manifests
    targetRevision: HEAD
  syncPolicy:
    automated: {}
   # Define the application parameters
  sourceType: Helm
  helm:
    valueFiles:
      - values.yaml
